project_name: kspec

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: kspec
    main: ./cmd/kspec
    binary: kspec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    flags:
      - -trimpath

  - id: manager
    main: ./cmd/manager
    binary: manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: kspec-archive
    builds:
      - kspec
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/*
      - specs/examples/*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - 'README'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: cloudcwfranck
    name: kspec
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## kspec {{ .Version }}

    **Ship a cluster spec, not a platform.**

    Kubernetes Cluster Compliance Enforcer - validates clusters against versioned specifications, enforces security policies, and monitors for configuration drift.

    ### What's in this release

    ✅ **Phase 1-6 Complete**
    - 🔍 Cluster Security Scanning (14 comprehensive checks)
    - 📋 Cluster Specification (ClusterSpecification CRD)
    - 🛡️ Policy Enforcement (Kyverno integration)
    - 🎯 Drift Detection & Auto-Remediation
    - 📊 Compliance Reporting
    - 🔄 Continuous Monitoring
  footer: |
    ## Installation

    ### Quick Install (Linux/macOS)

    ```bash
    # Linux x86_64
    curl -L https://github.com/cloudcwfranck/kspec/releases/download/{{ .Tag }}/kspec_{{ .Version }}_Linux_amd64.tar.gz | tar xz
    sudo mv kspec /usr/local/bin/

    # macOS Apple Silicon
    curl -L https://github.com/cloudcwfranck/kspec/releases/download/{{ .Tag }}/kspec_{{ .Version }}_Darwin_arm64.tar.gz | tar xz
    sudo mv kspec /usr/local/bin/

    # macOS Intel
    curl -L https://github.com/cloudcwfranck/kspec/releases/download/{{ .Tag }}/kspec_{{ .Version }}_Darwin_amd64.tar.gz | tar xz
    sudo mv kspec /usr/local/bin/
    ```

    ### Verify Installation

    ```bash
    kspec version
    ```

    ## Quick Start

    ```bash
    # 1. Scan your cluster for security issues
    kspec scan --output-format=text

    # 2. Generate a cluster specification from current state
    kspec scan --output-format=spec > cluster-spec.yaml

    # 3. Enforce security policies with Kyverno
    kspec enforce --spec cluster-spec.yaml

    # 4. Detect configuration drift
    kspec drift detect --spec cluster-spec.yaml

    # 5. Auto-remediate drift
    kspec drift remediate --spec cluster-spec.yaml
    ```

    ## Documentation

    - 📚 [Getting Started Guide](https://github.com/cloudcwfranck/kspec/blob/main/README.md)
    - 🔍 [Security Scanning](https://github.com/cloudcwfranck/kspec/blob/main/docs/SCANNING.md)
    - 🛡️ [Policy Enforcement](https://github.com/cloudcwfranck/kspec/blob/main/docs/ENFORCEMENT.md)
    - 🎯 [Drift Detection](https://github.com/cloudcwfranck/kspec/blob/main/docs/DRIFT_DETECTION.md)
    - 📋 [Examples](https://github.com/cloudcwfranck/kspec/tree/main/specs/examples)

    ---

    **Full Changelog**: https://github.com/cloudcwfranck/kspec/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker images for operator
dockers:
  - ids:
      - manager
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/cloudcwfranck/kspec-operator:{{ .Version }}"
      - "ghcr.io/cloudcwfranck/kspec-operator:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=kspec-operator"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/cloudcwfranck/kspec"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--platform=linux/amd64"

announce:
  skip: true
